### ISSUE TITLE
read issue

### ISSUE THREAD

**Issue by raylooi** [dangweili/pedestrian-attribute-recognition-pytorch#21]
(python2-env) D:\codes\pedestrian-attribute-recognition-pytorch-master>python transform_peta.py
Traceback (most recent call last):
  File "transform_peta.py", line 83, in <module>
    generate_data_description(save_dir)
  File "transform_peta.py", line 28, in generate_data_description
    data = loadmat(open('./dataset/peta/PETA.mat', 'r'))
  File "D:\Anaconda\envs\python2-env\lib\site-packages\scipy\io\matlab\mio.py", line 208, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "D:\Anaconda\envs\python2-env\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "D:\Anaconda\envs\python2-env\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 723, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 969, in scipy.io.matlab.mio5_utils.VarReader5.read_struct
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 705, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 778, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 195, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 171, in scipy.io.matlab.streams.ZlibInputStream.read_into
  File "streams.pyx", line 158, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -3 while decompressing: invalid distance too far back

**Comment by raylooi** [comment]
any idea where this error is about ?

**Comment by dangweili** [comment]
I have no idea about this error~
